apiVersion: v1

kind: Service

metadata:
  name: "service-nodeapp-prod"
  labels:
    contentname: "client.web.service"


spec:
  selector:
    nodeapptype: "clientapp"

  type: "NodePort"
  ports:
    - port: 3050 ### Opening for another pod to reach the service running on 3000
      targetPort: 3000 ### Port inside the pod that we want to expose and where the service is running in the container
      nodePort: 31515 ### if not specified, it will be a random number ranging from 30000 - 32767
