---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: multi-client-deployment

spec:

  replicas: 3
  selector:
    matchLabels:
      nodeapp: multi-client-pod
      component: web

  template:

    metadata:
      labels:
        nodeapp: multi-client-pod
        component: web


    spec:

      containers:
      - name: multi-client-app
        image: "knagadevara/node-app:client_dev_v.1"
        resources:
          limits:
            memory: "128Mi"
            cpu: "250m"
        ports:
        - containerPort: 3000