---
apiVersion: v1
kind: Service
metadata:
  name: multiClient_Service
spec:
  type: ClusterIP

  selector:
    nodeapp: multiClientPOD
  ports:
  - port: 3000 ##available to outside world on 
    targetPort: 3000 ## targeted container port