---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: multi-master-deployment

spec:

  replicas: 3
  selector:
    matchLabels:
      nodeapp: multi-master-pod
      component: web-master

  template:

    metadata:
      labels:
        nodeapp: multi-master-pod
        component: web-master

    spec:

      containers:
        - name: multi-master-app
          image: "knagadevara/node-app:master_dev_v.1"
          resources:
            limits:
              memory: "128Mi"
              cpu: "250m"
          ports:
          - containerPort: 5000