---
apiVersion: v1
kind: Service
metadata:
  name: multi-master-service
spec:
  type: ClusterIP

  selector:
    nodeapp: multi-master-pod
  ports:
  - port: 5000 ##available to outside world on 
    targetPort: 5000 ## targeted container port