---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: multi-master-deployment

spec:

  replicas: 3
  selector:
    matchLabels:
      nodeapp: multi-master-pod
      component: web-master

  template:

    metadata:
      labels:
        nodeapp: multi-master-pod
        component: web-master

    spec:

      containers:
        - name: multi-master-app
          image: "knagadevara/node-app:master_dev_v.1"
          resources:
            limits:
              memory: "128Mi"
              cpu: "250m"
          ports:
          - containerPort: 5000
            protocol: TCP          
          env:
            - name: "PGUSER"
              value: "postgres"
            - name: "PGPASSWORD"
              valueFrom:
                  secretKeyRef:
                    name: "pgpassword"
                    key: "PGPASSWORD" 
            - name: "PGHOST"
              value: "standalone-postgres-service"
            - name: "PGPORT"
              value: "5432"
            - name: "PGDATABASE"
              value: "postgres"
            - name: "REDIS_HOST"
              value: "standalone-redis-service"
            - name: "REDIS_PORT"
              value: "6379"            
            