---
apiVersion: v1
kind: Service
metadata:
  name: multiMaster_Service
spec:
  type: ClusterIP

  selector:
    nodeapp: multiMasterPOD
  ports:
  - port: 5000 ##available to outside world on 
    targetPort: 5000 ## targeted container port