---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: ns-cpu-mem-resource-quota
  namespace: <namespace>
spec:
  hard:
    requests.cpu: 4
    requests.memory: 4Gi
    limits.cpu: 10
    limits.memory: 10Gi